---
-   name: Provision Site
    hosts: all
    remote_user: root
    tasks:
        -   name: Update apt packages
            apt:
                update_cache: yes

        -   name: Install dependencies
            apt:
                name:
                    - apt-transport-https
                    - ca-certificates
                    - curl
                    - gnupg
                    - lsb-release
                state: present # зависимости должны быть свежими и установлены
                update_cache: yes # обновить apt кеш

        -   name: Add GPG key
            apt_key:
                url: https://download.docker.com/linux/debian/gpg
                state: present

        -   name: Set up the repository
            apt_repository:
                repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
                state: present
                filename: docker
                update_cache: yes

        -   name: Update apt packages
            apt:
                update_cache: yes

        -   name: Install Docker
            apt:
                name:
                    - docker-ce
                    - docker-ce-cli
                    - containerd.io
                state: present
                update_cache: yes
            notify: Start docker on boot

        -   name: Install Docker Compose
            get_url:
                url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
                dest: /usr/local/bin/docker-compose
                group: docker
                mode: 'u+x,g+x'

        -   name: Set periodic Docker prune
            cron:
                name: docker-prune
                job: 'docker system prune -f --filter "until=$((30*24))h"'
                minute: '0'
                hour: '1'

        -   name: Remove useless packages
            apt:
                autoclean: yes

        -   name: Remove useless dependencies
            apt:
                autoremove: yes

    handlers:
        -   name: Start docker on boot
            systemd:
                name: docker
                state: started
                enabled: yes